export const events = [
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Павильон книги',
    image: {
      code: 'moscow_ru',
      name: 'moscow_ru',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 4,
    relatedItems: 2,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_dk',
      name: 'aalborg_dk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
  {
    label: 'Рекомендация',
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'paris_fr',
      name: 'paris_fr',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 12,
    relatedItems: 5,
  },
  {
    subTitle: 'test test',
    title: 'test test',
    caption: 'Выставка: мечты о море',
    name: 'Государственный Театр Наций',
    image: {
      code: 'aalborg_uk',
      name: 'aalborg_uk',
      original: '385x320',
      placeholder: '385x320',
    },
    time: '14:00-16:00',
    duration: '37 минут',
    price: '1500-3000',
    age: 0,
  },
];
